; Name: 		cos.ini
; Description: 	Simulation settings for tk/turkeli. Derived from config/cos.ini for testing;
;		use with: coslaunch.py -c config/simulation/tk/turkeli/cos.ini

[Folders]
ROOT=$(COS_ROOT)	            ; Set $(ROOT) environment variable
CONFIG=$(COS_ROOT)/config       ; Root directory for configuration file
DB=$(COS_ROOT)/config          ; Root directory for database files
Workspace=$(ROOT)/build
SourceFolder=$(ROOT)/build/source
StagingFolder=$(ROOT)/build/staging

[EnvironmentVariables]      ; Simulation profile settings
COUNTRY=tk
LOCATION=turkeli
WEATHER=clearsky
TRAFFIC=ldta,fleet
CASE=0
SIMULATION=$(CONFIG)/simulation/$(COUNTRY)/$(LOCATION)
MAP=$(CONFIG)/map/$(COUNTRY)/$(LOCATION)
SCENARIO=scenario-$(CASE):$(COUNTRY)/$(LOCATION)/$(WEATHER)/$(TRAFFIC)

[SystemUtilities.Logger]
ConfigurationFile=$(CONFIG)/logger.yaml
LogFile=$(ROOT)/build/syslog.s3db

[SystemUtilities.Metrics]
MetricsFile=$(ROOT)/build/metrics.s3db

[ProcessManager]
NumThreads=4
RunCycles=1000000

[Simulation]
Kernel=Subsystem
Faculties=Environment,Monitors,Signals,Actors,Rules
Services=NetworkServices


[Subsystem]
Level-0=$(CONFIG)/subsystem.yaml

[NetworkServices]
Local=$(CONFIG)/network.yaml
API=$(CONFIG)/api.yaml


[Rules]
COLREG=$(CONFIG)/rules.colreg.yaml
MASS=$(CONFIG)/rules.mass.yaml
LocalRules=$(CONFIG)/simulation/$(COUNTRY)/$(LOCATION)/rules.yaml
Competency=$(CONFIG)/rules.examiner.yaml
RiskAssessment=$(CONFIG)/rules.risk.yaml


[Signals]
Beacons=$(CONFIG)/beacon.yaml
Radars=$(CONFIG)/radar.yaml
PortAuthorities=$(CONFIG)/port.yaml
Mapping=$(CONFIG)/mapping.yaml

[Actors]
Vessels=$(CONFIG)/vessel.yaml

[Environment]
Land=$(CONFIG)/land.yaml
Sea=$(CONFIG)/sea.yaml
Sky=$(CONFIG)/sky.yaml
Weather=$(CONFIG)/weather.yaml

[Monitors]
Situation=$(CONFIG)/situation.yaml
Conduct=$(CONFIG)/conduct.yaml
Evaluator=$(CONFIG)/evaluator.yaml
