packages:
  modules:  # Land & geographical mapping
     - name: Builder.MAP
       module: cos.model.geography.MapBuilder
       service: Builder.MAP
       args: 
       database: $(MAP)/land.s3db

     - name: Builder.MOUNTAIN
       module: cos.model.geography.LandBuilder
       service: Builder.MOUNTAIN
       args: Type=MOUNTAIN
       database: $(MAP)/land.s3db

     - name: Builder.PLAIN
       module: cos.model.geography.LandBuilder
       service: Builder.PLAIN
       args: Type=PLAIN
       database: $(MAP)/land.s3db

     - name: Builder.PLATEAU
       module: cos.model.geography.LandBuilder
       service: Builder.PLATEAU
       args: Type=PLATEAU
       database: $(MAP)/land.s3db

     - name: Builder.DESERT
       module: cos.model.geography.LandBuilder
       service: Builder.DESERT
       args: Type=DESERT
       database: $(MAP)/land.s3db
